### predict labels endpoint
POST {{host}}/predict
accept: application/json
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="sample.csv"

< sample.csv
--WebAppBoundary--

###

